import type {
  ProductListItem,
  ProductDetail,
  CategoryWithChildren,
} from "~/types";

// Mock products + categories used as a fallback when the OneApp Storefront API
// (ONEAPP_API_URL / ONEAPP_API_KEY in .env) is unconfigured or returns nothing.
// They let us preview the shop and product-detail layouts without a live API.
// Real data takes over automatically once the API returns results.

export const DEMO_CATEGORY_TREE: CategoryWithChildren[] = [
  {
    id: -100,
    categoryName: "First Aid Kits",
    parentCategoryId: null,
    amazonCategoryId: null,
    walmartCategoryId: null,
    wooCommerceCategoryId: null,
    ebayCategoryId: null,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    children: [],
    productCount: 3,
    mergedCategoryIds: [-100],
  },
  {
    id: -101,
    categoryName: "Bleeding Control",
    parentCategoryId: null,
    amazonCategoryId: null,
    walmartCategoryId: null,
    wooCommerceCategoryId: null,
    ebayCategoryId: null,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    children: [],
    productCount: 2,
    mergedCategoryIds: [-101],
  },
  {
    id: -102,
    categoryName: "Training Equipment",
    parentCategoryId: null,
    amazonCategoryId: null,
    walmartCategoryId: null,
    wooCommerceCategoryId: null,
    ebayCategoryId: null,
    createdAt: new Date(0),
    updatedAt: new Date(0),
    children: [],
    productCount: 1,
    mergedCategoryIds: [-102],
  },
];

export const DEMO_PRODUCTS: ProductDetail[] = [
  {
    id: -1001,
    slug: "loggers-first-aid-kit",
    name: "Loggers First Aid Kit",
    description:
      "<p>Built for crews working in the woods. Compact, ANSI-compliant, and stocked with the trauma supplies you actually need when help is hours away.</p>",
    brandName: "TNT First Aid",
    brandId: -1,
    categoryName: "First Aid Kits",
    categoryId: -100,
    primaryImage: "/images/hero/kit-red-bag.png",
    fallbackImage: "/images/hero/kit-contents.png",
    price: 4999,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 5,
    totalReviews: 12,
    bulletPoints: [
      "OSHA & ANSI Z308.1 compliant",
      "Includes tourniquet, hemostatic gauze, and trauma dressing",
      "Weatherproof MOLLE-compatible bag",
      "Restock list and quick-reference guide included",
    ],
    keywords: "loggers, first aid kit, OSHA, ANSI, trauma",
    images: [
      "/images/hero/kit-red-bag.png",
      "/images/hero/kit-contents.png",
      "/images/hero/kit-full-spread.png",
      "/images/hero/kit-packed.png",
    ],
    variations: [
      {
        id: -10011,
        manufacturerNo: "TNT-LOG-001",
        variantType: null,
        variation: null,
        variantTypeTwo: null,
        variationTwo: null,
        price: 4999,
        msrp: null,
        map: null,
        weight: 3.2,
        images: ["/images/hero/kit-red-bag.png"],
        inStock: true,
        quantity: 24,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
  {
    id: -1002,
    slug: "stop-the-bleed-kit",
    name: "STOP The Bleed Kit",
    description:
      "<p>Everything a bystander needs to control life-threatening bleeding before EMS arrives. Designed around the national STOP The Bleed campaign.</p>",
    brandName: "TNT First Aid",
    brandId: -1,
    categoryName: "Bleeding Control",
    categoryId: -101,
    primaryImage: "/images/hero/kit-contents.png",
    fallbackImage: "/images/hero/kit-red-bag.png",
    price: 6800,
    msrp: 7500,
    map: null,
    inStock: true,
    variationCount: 2,
    averageRating: 4.5,
    totalReviews: 21,
    bulletPoints: [
      "CAT Gen 7 tourniquet (TCCC-recommended)",
      "Compressed gauze with kaolin clotting agent",
      "Trauma shears, gloves, and permanent marker",
      "Vacuum-sealed for long shelf life",
    ],
    keywords: "stop the bleed, tourniquet, hemostatic, trauma kit",
    images: [
      "/images/hero/kit-contents.png",
      "/images/hero/kit-red-bag.png",
      "/images/hero/kit-full-spread.png",
    ],
    variations: [
      {
        id: -10021,
        manufacturerNo: "TNT-STB-BASIC",
        variantType: "Configuration",
        variation: "Basic",
        variantTypeTwo: null,
        variationTwo: null,
        price: 6800,
        msrp: 7500,
        map: null,
        weight: 1.4,
        images: ["/images/hero/kit-contents.png"],
        inStock: true,
        quantity: 47,
        packCount: 1,
      },
      {
        id: -10022,
        manufacturerNo: "TNT-STB-PRO",
        variantType: "Configuration",
        variation: "Pro (with chest seal)",
        variantTypeTwo: null,
        variationTwo: null,
        price: 8900,
        msrp: 9800,
        map: null,
        weight: 1.7,
        images: ["/images/hero/kit-full-spread.png"],
        inStock: true,
        quantity: 19,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
  {
    id: -1003,
    slug: "coaches-first-aid-kit",
    name: "Coaches First Aid Kit",
    description:
      "<p>The sideline kit chosen by youth and high-school athletic programs across the country. Stocked for sprains, lacerations, abrasions, and the occasional bloody nose.</p>",
    brandName: "TNT First Aid",
    brandId: -1,
    categoryName: "First Aid Kits",
    categoryId: -100,
    primaryImage: "/images/hero/kit-full-spread.png",
    fallbackImage: "/images/hero/kit-packed.png",
    price: 4500,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 4.8,
    totalReviews: 15,
    bulletPoints: [
      "Stocked for 25+ student-athletes",
      "Cold packs, ace wrap, and athletic tape",
      "Bandages, antiseptic wipes, and burn gel",
      "Bright-red zippered bag with carry handle",
    ],
    keywords: "coach, sideline, sports first aid, athletic kit",
    images: [
      "/images/hero/kit-full-spread.png",
      "/images/hero/kit-packed.png",
      "/images/hero/kit-contents.png",
    ],
    variations: [
      {
        id: -10031,
        manufacturerNo: "TNT-CCH-001",
        variantType: null,
        variation: null,
        variantTypeTwo: null,
        variationTwo: null,
        price: 4500,
        msrp: null,
        map: null,
        weight: 2.5,
        images: ["/images/hero/kit-full-spread.png"],
        inStock: true,
        quantity: 31,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
  {
    id: -1004,
    slug: "naloxone-filled-kit",
    name: "Naloxone Filled Kit",
    description:
      "<p>Wall-mountable opioid response station with two doses of intranasal naloxone, rescue breathing barrier, gloves, and step-by-step instructions.</p>",
    brandName: "TNT First Aid",
    brandId: -1,
    categoryName: "First Aid Kits",
    categoryId: -100,
    primaryImage: "/images/hero/kit-packed.png",
    fallbackImage: "/images/hero/cpr-mask-kit.png",
    price: 8900,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 5,
    totalReviews: 8,
    bulletPoints: [
      "Two 4mg intranasal naloxone doses",
      "CPR rescue breathing barrier",
      "Tamper-evident seal with replacement indicator",
      "Compliant with most state Good Samaritan programs",
    ],
    keywords: "naloxone, narcan, opioid, overdose response",
    images: [
      "/images/hero/kit-packed.png",
      "/images/hero/cpr-mask-kit.png",
      "/images/hero/kit-contents.png",
    ],
    variations: [
      {
        id: -10041,
        manufacturerNo: "TNT-NAL-001",
        variantType: null,
        variation: null,
        variantTypeTwo: null,
        variationTwo: null,
        price: 8900,
        msrp: null,
        map: null,
        weight: 1.1,
        images: ["/images/hero/kit-packed.png"],
        inStock: true,
        quantity: 12,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
  {
    id: -1005,
    slug: "cat-gen-7-tourniquet",
    name: "CAT Gen 7 Tourniquet",
    description:
      "<p>The Combat Application Tourniquet, Gen 7 — the only tourniquet recommended by the Committee on Tactical Combat Casualty Care for both military and civilian use.</p>",
    brandName: "North American Rescue",
    brandId: -2,
    categoryName: "Bleeding Control",
    categoryId: -101,
    primaryImage: "/images/hero/kit-contents.png",
    fallbackImage: "/images/hero/kit-red-bag.png",
    price: 3299,
    msrp: 3500,
    map: null,
    inStock: true,
    variationCount: 3,
    averageRating: 4.9,
    totalReviews: 184,
    bulletPoints: [
      "TCCC-recommended for limb hemorrhage control",
      "True one-handed application",
      "Reinforced single-routing buckle",
      "Available in black, orange (high-vis), and tan",
    ],
    keywords: "CAT tourniquet, gen 7, NAR, tourniquet, TCCC",
    images: [
      "/images/hero/kit-contents.png",
      "/images/hero/kit-red-bag.png",
      "/images/hero/kit-full-spread.png",
    ],
    variations: [
      {
        id: -10051,
        manufacturerNo: "NAR-CAT7-BLK",
        variantType: "Color",
        variation: "Black",
        variantTypeTwo: null,
        variationTwo: null,
        price: 3299,
        msrp: 3500,
        map: null,
        weight: 0.18,
        images: ["/images/hero/kit-contents.png"],
        inStock: true,
        quantity: 86,
        packCount: 1,
      },
      {
        id: -10052,
        manufacturerNo: "NAR-CAT7-ORG",
        variantType: "Color",
        variation: "Orange (Hi-Vis)",
        variantTypeTwo: null,
        variationTwo: null,
        price: 3299,
        msrp: 3500,
        map: null,
        weight: 0.18,
        images: ["/images/hero/kit-red-bag.png"],
        inStock: true,
        quantity: 42,
        packCount: 1,
      },
      {
        id: -10053,
        manufacturerNo: "NAR-CAT7-TAN",
        variantType: "Color",
        variation: "Tan",
        variantTypeTwo: null,
        variationTwo: null,
        price: 3299,
        msrp: 3500,
        map: null,
        weight: 0.18,
        images: ["/images/hero/kit-full-spread.png"],
        inStock: false,
        quantity: 0,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
  {
    id: -1006,
    slug: "cpr-mask-training-kit",
    name: "CPR Mask Training Kit",
    description:
      "<p>Practice rescue breathing the way you'd actually do it. Adult and infant pocket masks with one-way valves, hard case, and a quick-reference card.</p>",
    brandName: "TNT First Aid",
    brandId: -1,
    categoryName: "Training Equipment",
    categoryId: -102,
    primaryImage: "/images/hero/cpr-mask-kit.png",
    fallbackImage: "/images/hero/kit-packed.png",
    price: 2799,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 4.7,
    totalReviews: 33,
    bulletPoints: [
      "Adult + infant pocket masks with one-way valves",
      "Hard plastic case with belt loop",
      "Latex-free, single-use components",
      "Includes laminated step-by-step CPR card",
    ],
    keywords: "CPR mask, pocket mask, training, rescue breathing",
    images: [
      "/images/hero/cpr-mask-kit.png",
      "/images/hero/kit-packed.png",
      "/images/hero/kit-contents.png",
    ],
    variations: [
      {
        id: -10061,
        manufacturerNo: "TNT-CPR-MSK",
        variantType: null,
        variation: null,
        variantTypeTwo: null,
        variationTwo: null,
        price: 2799,
        msrp: null,
        map: null,
        weight: 0.6,
        images: ["/images/hero/cpr-mask-kit.png"],
        inStock: true,
        quantity: 58,
        packCount: 1,
      },
    ],
    relatedProducts: [],
  },
];

// Strip detail-only fields for list/grid views.
export const DEMO_PRODUCT_LIST_ITEMS: ProductListItem[] = DEMO_PRODUCTS.map(
  ({ bulletPoints, keywords, images, variations, relatedProducts, ...item }) =>
    item,
);

export function getDemoProductBySlug(slug: string): ProductDetail | null {
  const product = DEMO_PRODUCTS.find((p) => p.slug === slug);
  if (!product) return null;
  // Populate related products with up to 3 other demo products
  const related: ProductListItem[] = DEMO_PRODUCT_LIST_ITEMS.filter(
    (p) => p.slug !== slug,
  ).slice(0, 3);
  return { ...product, relatedProducts: related };
}
