import type { ProductListItem } from "~/types";

// Fallback so the featured section is visible while the OneApp API
// (ONEAPP_API_URL / ONEAPP_API_KEY in .env) is still using placeholder values.
// Real featured products take over automatically once the API returns data.
export const DEMO_FEATURED_PRODUCTS: ProductListItem[] = [
  {
    id: -1,
    slug: "loggers-first-aid-kit",
    name: "Loggers First Aid Kit",
    description: null,
    brandName: null,
    brandId: null,
    categoryName: null,
    categoryId: null,
    primaryImage: null,
    fallbackImage: null,
    price: 4999,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 5,
    totalReviews: 12,
  },
  {
    id: -2,
    slug: "naloxone-filled-kit",
    name: "Naloxone Filled Kit",
    description: null,
    brandName: null,
    brandId: null,
    categoryName: null,
    categoryId: null,
    primaryImage: null,
    fallbackImage: null,
    price: 8900,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 5,
    totalReviews: 8,
  },
  {
    id: -3,
    slug: "stop-the-bleed-kit",
    name: "STOP The Bleed Kit",
    description: null,
    brandName: null,
    brandId: null,
    categoryName: null,
    categoryId: null,
    primaryImage: null,
    fallbackImage: null,
    price: 6800,
    msrp: 7500,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 4.5,
    totalReviews: 21,
  },
  {
    id: -4,
    slug: "coaches-first-aid-kit",
    name: "Coaches First Aid Kit",
    description: null,
    brandName: null,
    brandId: null,
    categoryName: null,
    categoryId: null,
    primaryImage: null,
    fallbackImage: null,
    price: 4500,
    msrp: null,
    map: null,
    inStock: true,
    variationCount: 1,
    averageRating: 4.8,
    totalReviews: 15,
  },
];
